spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/talent_hub}
    username: ${DB_USERNAME:talent_user}
    password: ${DB_PASSWORD:talent_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  docker:
    compose:
      enabled: true
      file: ./compose.yaml

app:
  security:
    demo:
      email: ${APP_SECURITY_DEMO_EMAIL:kaique.simao@talenthub.com}
      password: ${APP_SECURITY_DEMO_PASSWORD:TalentHub@123}
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:talent-hub-local-dev-secret-key-with-32chars}
      ttl: ${APP_SECURITY_JWT_TTL:8h}

logging:
  level:
    org.hibernate.SQL: warn
    org.flywaydb: info
